version: "3"

services:
  server:
    image: gitea/gitea:1.16.8
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=172.18.0.3:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=fc71IAAk
    restart: always
    networks:
      mynetwork:
        ipv4_address: 172.18.0.5
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

