version: '3'

networks:
#  mynetwork1:
#    external: true
#
#  mynetwork2:
#    external:
#      name: "test_mynet"

  mynetwork3:
    name: mynetwork3
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16