version: '3'

services:
  hello-world:
    container_name: hello-world
    image: hello-world
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2


networks:
  mynetwork:
    name: mynetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16