version: '3.1'

services:

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4

networks:
  mynetwork:
    external: true
