version: '3'
services:

  nginx:
    container_name: mynginx
    build:
      context: ./build
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./conf/conf.d:/etc/nginx/conf.d:rw
      - ./log:/var/log/nginx:rw
    networks:
      mynetwork:
        ipv4_address: 172.19.18.17

networks:
  mynetwork:
    external: true