version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - /home:/home:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./conf/conf.d:/etc/nginx/conf.d:rw
      - ./log:/var/log/nginx:rw
    ports:
      - 8888:8888
    networks:
      mynetwork:
        ipv4_address: 172.18.0.8

networks:
  mynetwork:
    external: true
