version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.29
    volumes:
      - ${PROJECT_FOLDER}:/home/app:rw
      - ./conf:/etc/mysql/conf.d:rw
      - ./data:/var/lib/mysql:rw
      - ./log:/var/log/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
#    command: