version: '3'
services:
  mysql:
    container_name: mysql3
    image: mysql:8.0.25
    volumes:
      - ./conf:/etc/mysql/conf.d:rw
      - ./data:/var/lib/mysql:rw
      - ./log:/var/log/mysql:rw
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

networks:
  mynetwork:
    external: true