version: '3'
services:

  nginx:
    container_name: elasticsearch-kibana12

    image: docker.elastic.co/kibana/kibana:6.8.20
    restart: always
#    ports:
#      - 5601:5601
#    volumes:
#      - ./conf:/usr/share/kibana/config:rw

    environment:
      - ELASTICSEARCH_URL=http://172.18.0.11:9200

    networks:
      mynetwork:
        ipv4_address: 172.18.0.12

networks:
  mynetwork:
    external: true




# docker run --name kib01-test --net elastic -p 127.0.0.1:5601:5601 -e "ELASTICSEARCH_HOSTS=http://es01-test:9200" docker.elastic.co/kibana/kibana:7.15.2