version: '3'
services:

  nginx:
    container_name: php6
    build:
      context: ./php
#    image: php:7.4.6-fpm
    restart: always
    volumes:
      - /home:/home:rw
#    working_dir: /home
    networks:
      mynetwork:
        ipv4_address: 172.18.0.6

networks:
  mynetwork:
    external: true


# pecl install -o -f redis && rm -rf /tmp/pear && docker-php-ext-enable redis
# prcl install -o -f mongodb && rm -rf /tmp/pear && docker-php-ext-enable mongodb
#docker-php-ext-install mysqli pdo pdo_mysql