version: '3'
services:
  mongo:
    container_name: mongo3
    image: mongo:4.2.8
    volumes:
      - ./data:/data/db:rw
    restart: always
    ports:
      - 27017:27017
    networks:
      mynetwork:
        ipv4_address: 172.18.0.8
    command: --auth

networks:
  mynetwork:
    external: true